### ISSUE TITLE
Stack subdirs don't work too well

### ISSUE THREAD

**Issue by hasufell** [edsko/stack2cabal#8]
```yaml
packages:
  - .
  - location:
      git: https://github.com/brendanhay/amazonka
      commit: a3eabd987287bd5117faa07cb2875bad2ed9ae21
    subdirs:
      - amazonka
      - core
      - amazonka-secretsmanager
      - amazonka-s3
    extra-dep: true
```

Becomes:

```
source-repository-package
    type: git
    location: https://github.com/brendanhay/amazonka
    tag: a3eabd987287bd5117faa07cb2875bad2ed9ae21
```
